import type { Metadata } from "next";
import {  Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { ThemeProvider } from "@/components/themeProvider"
import { cn } from "@/lib/utils";
// import Navbar from "@/components/navbar";
import { UserProvider } from "@/context/UserProvider";
const inter = Inter({ subsets : ['latin']})

export const metadata: Metadata = {
  title: "Next Platform",
  description: "Generated by Next Platform",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
        className={cn('min-h-screen font-sans antialiased grainy', inter.className)}
      >
         <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >

         {/* <Navbar/> */}
         <UserProvider>
        {children}
         </UserProvider>
        <ToastContainer />
          </ThemeProvider>
      </body>
    </html>
  );
}
